---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      network:
        - ['forwarded_port', {guest: 80, host: 8080}]
suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[chef-example::default]
    attributes:
